apiVersion: apps/v1
kind: Deployment
metadata:
  name: instaprotek-app
  namespace: instaprotek
  labels:
    app: instaprotek-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: instaprotek-app
  template:
    metadata:
      labels:
        app: instaprotek-app
    spec:
      containers:
        - name: instaprotek-container
          image: irfan611/my-image-name:1745519265  # <-- Replace with your actual image tag if needed
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: development
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
