apiVersion: v1
kind: Service
metadata:
  name: instaprotek-service
  namespace: instaprotek
  labels:
    app: instaprotek-app
spec:
  selector:
    app: instaprotek-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: https-internal
    port: 443
    protocol: TCP
    targetPort: 3000
  type: ClusterIP
