apiVersion: v1
kind: Service
metadata:
  name: instaprotek-service
  namespace: instaprotek
  labels:
    app: instaprotek-app
spec:
  selector:
    app: instaprotek-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
